name: nmap23
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs=18
  - ipywidgets==8.*   # https://github.com/jupyter-widgets/ipywidgets
#  - jupyter-offlinenotebook==0.2.*   # https://github.com/manics/jupyter-offlinenotebook
#  - jupyter-resource-usage==0.7.*   # https://github.com/jupyter-server/jupyter-resource-usage
#  - jupyter_server==1.*   # https://github.com/jupyter-server/jupyter_server
#  - jupyterhub-singleuser==3.*   # https://github.com/jupyterhub/jupyterhub
#  - jupyterlab==3.*   # https://github.com/jupyterlab/jupyterlab
#  - notebook==6.*   # https://github.com/jupyter/notebook
  # user
  - numpy==1.23.4
  - scipy==1.9.3
  - matplotlib==3.6.2
  - seaborn==0.12.1
  - rise==5.7.1
  - future==0.18.2
  - mpmath==1.3.0
  - pip
  - pip:
    - tqdm==4.66.1
    - PyNAFF==1.1.5
    - Cython==3.0.5
      #- PyHEADTAIL==1.16.1
    - cpymad ==1.14.2
    - pysixtrack ==0.0.6
    - botorch==0.8.1
    - cheetah-accelerator==0.5.18
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==1.13.1
    - gym==0.26.2
    - scikit-image==0.19.3
    - pillow==9.2.0
    - longitudinal-tomography==3.4.3
    - tensorflow-cpu==2.11.0
    - prettytable==3.6.0
    - stable_baselines3==2.2.1
