name: nmap23
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs=18
  - ipywidgets==8.*   # https://github.com/jupyter-widgets/ipywidgets
#  - jupyter-offlinenotebook==0.2.*   # https://github.com/manics/jupyter-offlinenotebook
#  - jupyter-resource-usage==0.7.*   # https://github.com/jupyter-server/jupyter-resource-usage
#  - jupyter_server==1.*   # https://github.com/jupyter-server/jupyter_server
#  - jupyterhub-singleuser==3.*   # https://github.com/jupyterhub/jupyterhub
#  - jupyterlab==3.*   # https://github.com/jupyterlab/jupyterlab
#  - notebook==6.*   # https://github.com/jupyter/notebook
  # user
  - numpy==1.23.4
  - scipy==1.9.3
  - matplotlib==3.6.2
  - seaborn==0.12.1
  - rise==5.7.1
  - future==0.18.2
  - mpmath
  - pip
  - pip:
    - PyNAFF==1.1.5
