name: nmap23
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs=18
  - pip
#  - ipywidgets==8.*   # https://github.com/jupyter-widgets/ipywidgets
#  - jupyter-offlinenotebook==0.2.*   # https://github.com/manics/jupyter-offlinenotebook
#  - jupyter-resource-usage==0.7.*   # https://github.com/jupyter-server/jupyter-resource-usage
#  - jupyter_server==1.*   # https://github.com/jupyter-server/jupyter_server
#  - jupyterhub-singleuser==3.*   # https://github.com/jupyterhub/jupyterhub
#  - jupyterlab==3.*   # https://github.com/jupyterlab/jupyterlab
#  - notebook==6.*   # https://github.com/jupyter/notebook
  # user
  - numpy #==1.22.0
  - scipy #==1.7.3
  - matplotlib #==3.5.3
  - seaborn #==0.12.0
  - rise #==5.5.1
